# add postgressql service
version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neophiler
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

